### ISSUE TITLE
Generateblocks when is disabled leaves a message " Your site does not support generateblocks/container" 

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generateblocks#1027]
This is simple to recreate just add a simple container and a H1 or Paragraph blocks and disable Generateblocks later. Done this with PRO and FREE versions, both do the same. 

This is an issue as it locks in the content to generateblocks plugin, is an issue that had many plugins in the past and still have as Elementor etc.  I remember comments from Tom which where right to judge this kind of plugins, and now GB does the same "mistake".

In my honest opinion this is very serious and will make a user to consider if he will use GB in the future projects as Gutenberg envolves, so please take a look on this one.

**Comment by tomusborne** [comment]
Hi @FunkyCss,

This is a core WordPress behavior that will happen with any block plugin - it's not something that GenerateBlocks does or has any control over.

The nice thing about GenerateBlocks specifically is that you can click "Keep as HTML", then click the three dots and "Convert to Blocks". This works because GenerateBlocks doesn't leave behind any unnecessary HTML.

**Comment by FunkyCss** [comment]
Hi, I see.. I will leave a comment from one very active wordpress group on facebook from a guy that has put it perfectly.

"Yeah, in a way this isn't that much better than the short codes from visual composer back in the day. My gut feeling was always that block libraries are in itself a lock in. The only upside … WordPress offers a unifying platform with Gutenberg that runs all sorts of blocks. The safes approach is to rely on base blocks included in WordPress. "

**Comment by tomusborne** [comment]
I don't see it this way. When a plugin like that was deactivated, all content went along with it as the content was stored in plugin-specific fields that only displayed using the shortcodes.

All content in GenerateBlocks is stored with your other post content. If GenerateBlocks goes away, your content still remains along with the rest of your non-GenerateBlocks content. The only difference is that the editor displays the message telling you the block no longer exists (because you've removed it). The content still shows on the frontend, and can be easily recovered in the editor.

In the future, it would be nice if WordPress made it even easier to recover the content, although it's a good thing they display the message saying the block no longer exists to make you aware in case it was a mistake.
