### ISSUE TITLE
GB 2.0 Pre-alpha Image block in responsive views requires max-width containment

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1384]
Image blocks have no max-width control within responsive views, resulting in unwanted overflow:

<img width="1435" alt="Screenshot 2024-10-21 at 15 48 06" src="https://github.com/user-attachments/assets/6c00a443-6f90-48b1-bbe8-b075ceff3d84">

**Comment by iansvo** [comment]
I added a PR for this which applies max-width, height, and object-fit by default to the images. 

I think adding object-fit makes sense here also because 99% of the time, this is the desired behavior, especially for someone who doesn't know CSS. The default behavior for the img tag is not intuitive and someone can always change it if that is somehow what they actually want.

**Comment by iansvo** [comment]
Resolved in #1389
