### ISSUE TITLE
GB 2.0 - Toolbar - missing align / justffy / float button 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1408]
### Description
The toolbar button for text-alignment and image floats are missing from GB 2.0 blocks
For reference these are the the 1.0 toolbar buttons:

<img width="495" alt="Screenshot 2024-10-29 at 18 59 54" src="https://github.com/user-attachments/assets/9d698950-78fa-4ccd-b088-48c33d6ff383">
<img width="563" alt="Screenshot 2024-10-29 at 19 00 06" src="https://github.com/user-attachments/assets/7b5df05e-8ac7-4210-9c8b-a544024e8ae0">

**Comment by iansvo** [comment]
@tomusborne Do you hate the idea of just...using the same thing? It seems like this was working previously. 

@diggeddy Is there an alternative implementation to the previous one that makes sense?

**Comment by diggeddy** [comment]
A better implementation would be to include Floats as a property in the style tab.
We can leave the toolbar option out, as that would suggest the chosen option "will" work on the chosen block. When that is not necessary the case  eg. `text-alignment` on the `figure` vs `img` ....

**Comment by tomusborne** [comment]
I've added text align to the Container and Text blocks, as well as wide/full align support to the Container block. It should be easy to add these to other blocks as well if we want (although I hope we don't have to add wide/full support to any others lol).

I reverted my changes to add float to the image block. Using `float` was causing some issues in the editor that were tricky (but not impossible) to figure out. However, there's a bigger issue (that @diggeddy mentioned above) of what happens when you float an image inside of a caption. Really, you should be floating the surrounding block instead of the image. Not sure how we want to approach that.

a) We add the float alignment to the `Figure` and remove from the image if it has a figure.
b) We check if a figure exists when we use the float options in the image, and target that block to set the floats instead of the image.

**Comment by iansvo** [comment]
My only concern is that someone may want to use an image container that isn't a figure. So we ideally need some way to indicate the wrapper is related to the image. 

I would strongly caution against making assumptions about markup structure that we don't actually enforce.

**Comment by tomusborne** [comment]
Floating in the editor can cause some issues without additional logic (weird z-index things), but I think we can go ahead and do it. I'm assuming we'd need a `float` and `clear` option?

**Comment by diggeddy** [comment]
> I'm assuming we'd need a float and clear option?

Yeah we need both. We already `display: flow-root` so thats in place.
