### ISSUE TITLE
Read more manual without space after truncated text

### ISSUE THREAD

**Issue by andresbrx** [tomusborne/generateblocks#1591]
### Description
When using GB's default Read More, there is a space between the truncated text and the Read More link, but when using the manual text for Read More, GB shows the space in the builder, but on the front end there is no space.

#### Expected behavior
![image](https://github.com/user-attachments/assets/eb960f86-4aed-40e2-8dd9-54c39c77ca3c)
![image](https://github.com/user-attachments/assets/e533e4f8-81e1-49f0-ae08-e0a6faa0b9f5)

#### Actual behavior
![image](https://github.com/user-attachments/assets/4c1a8827-4c23-4de2-a39f-2ffa32607841)

-----

**Comment by iansvo** [comment]
@BrightsolNL I'm seeing the opposite of your comment: if I set a manual excerpt on a post there is no truncation or "read more" output, where if the excerpt is generated from post_content it works as expected. 

This lines up with core behavior: a manual excerpt is treated differently than one that is auto-generated from post content. If you look at the function wp_trim_excerpt, you can see it actually checks if the excerpt is empty before doing basically everything inside the function. 

That said, if you're using manual excerpts throughout, you could plan for that and just use the `trim` filter on your dynamic tag like so:

```
{{post_excerpt trunc:55,words}}
```

You will need to add ellipsis yourself and the read more link, but if you're using those consistently that should effectively get you the same result. Otherwise you may need to look into some custom PHP filters.
