### ISSUE TITLE
Query loop - ability to select multiple post types and dynamic/related param options 

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#370]
Based on my early testing the new query loop is looking really great and will solve a lof of problems I have outputting lists of content. I do have a couple of thoughts though on improvements to make it even more flexible based on some experience using other similar post loop / grid listing builders.

The main one is it would be good if there was a method to select more than one post type. I see in the param options post type is an option but it is greyed out because we have the post type selector above which I can only seem to select one post type at a time. It would nice if there was a way to perform a manual or multi post type selection? Maybe the dropdown has a manual/custom option and then we could utilise the greyed out post type option in params as a way to enter a manual array of post types we want? There's probably other ways it could be handled but that was one thought as it was there already. An example of this being useful is I might have a news and events post types which are separate, but in certain cases I might want list them out together.

Also I haven't been able to test this extensively but it would be nice if some of the param options could be given dynamic values relative to the page or template the loop is being displayed on. For example I might want ot use the query loop to create a related articles section at the bottom of a post. It would be great if there was as way we could dynamically specify related params such as related categories/taxonmies or post meta fields with same values etc to the currently viewed post/page. This would open up lots of usages within templates and sections of a site for outputting related content.

Thanks

**Comment by JeanPaiva** [comment]
Hey @eastriverstudio , thanks for you inputs.

1 - Possibility of having multiple post types per query loop, its a good feature as the `WP_Query` it self allows it.
But for the editor is tricky cause we use the core REST API to fetch data, and currently it's not supported. In order to enable this to be previewed by the user we need to customize the API endpoints to receive many post types.

2 - Currently, we have the option `Inherit query from template` which it works with GPP Elements and the FSE editor, but we definitely need more improvements on this. 

I'll be creating two separate tickets for each of this suggestions and put on our backlog for future versions.
