### ISSUE TITLE
Layout Panel doesn't open on first click

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#424]
See screenshot for reference:
https://www.screencast.com/t/pjoAbVcw0w

It would be better if the Layout panel auto opens on first click so users don't have to click layout, move the cursor, then click layout again.

**Comment by diggeddy** [comment]
Was just gonna post the Juggling Panel links ... whatever one is at the top when clicked moves below the other lol

https://user-images.githubusercontent.com/30641942/167174971-4327ce45-3713-4d9c-ba43-a55ee62e49ea.mov

**Comment by diggeddy** [comment]
And who knows where Documentation goes lol

**Comment by tomusborne** [comment]
The idea here was those panels act as shortcuts between the Query Loop and Grid blocks, which is why they both stay at the top. They simply switch between the two blocks.

We could put Layout below Query Parameters, but then it may get lost under all your parameter settings if you want to easily switch to the Grid block to adjust the Layout.
