### ISSUE TITLE
Grid flex-wrap options

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#499]
Current grid functionality always wraps the containers when the threshold point has been reached. It would be nice to have flex-wrap options available.

**Comment by eastriverstudio** [comment]
+1 for this. Obviously we can add some css for this simple enough but I always think it is nicer to control something relating to spacing and layout in the block settings rather than somewhere else. 

This addition would immediately make the grid easier to use as a custom carousel or slider etc. If option to set manually set overflow rule on container as has been suggested in rather feature ticket this would be very flexible for creating horizontally scrolling content etc.
