### ISSUE TITLE
Blocks visibility conditions

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#539]
It would be extremely useful to have improved container visibility conditions for the GB container. Right now, we can select to hide a container if no featured image is not uploaded for the post or if a custom field is empty. That is extremely limited. What about when we want to hide the container if **TWO** custom fields are missing? A container could house multiple custom fields that would all need to be empty for better container visibility. What if we wanted to hide the container if one **OR** another field is empty? I hope you see where I am going.

**Comment by JeanPaiva** [comment]
@quantumleap33 ye, we've talked about a more robust "display rules" system.

**Comment by eastriverstudio** [comment]
@quantumleap33 @JeanPaiva +1 for this as I ran into this very issue today and couldn’t do it with GB alone due to the limitations described. 

In fact I’d like to suggest this display rules logic is extended to not only the container but other blocks like headline. 

To give you a fairly simple example why this would be useful, today I wanted to have a field to override and hide the default page title if the field has a value and have this in a block element for all pages. However it wasn’t possible to hide the default title due to the container’s limited hide logic.

With the new dynamic features in GB this is definitely a needed feature.

Thanks

**Comment by jstask82** [comment]
> Right now, we can select to hide a container [...] if a custom field is empty.
That's only true for a block content template from generatepress. It is not available inside the query-loop block.

At least please bring over this feature from generatepress  block content template to the query-loop block. I guess that might be easy since this functionality already exist somewhere.

**Comment by JeanPaiva** [comment]
I created a pro version task to track this feature (Blocks display rules) to allow users to hide certain blocks based on some options or other blocks content. Gonna close this one to track only in the main task. Thank you

Reference: https://github.com/tomusborne/generateblocks-pro/issues/144
