### ISSUE TITLE
Container ID in editor view for 1.5.0-rc.1 

### ISSUE THREAD

**Issue by aaronbowden** [tomusborne/generateblocks#559]
### Description
When updating from 1.4.4 to 1.5.0-rc.1 I noticed that a containers ID (defined under HTML anchor) is no longer showing within the editor view.  Having the defined ID visible within the editor view has been helpful in styling to more closely match the front-end.

It's possible that this may not be a bug and there may be a reason for this change, but I wanted to raise the question as I'll need to make some tweaks to sites already built once 1.5.0 is official.

### Steps to reproduce
1. Add a Container Block and give it an ID.
2. Check the markup within the editor view.
3. Update from 1.4.4 to 1.5.0-rc.1
4. Check the markup within the editor view again and compare

#### Expected behavior
With 1.4.4 the ID is part of the Container's markup within the editor view.

#### Actual behavior
With 1.5.0-rc.1 the ID is no longer part of the Container's markup within the editor view.

#### References: 

Here is the container's markup with version 1.4.4

`<section class="gb-container gb-container-9aa050e7 gb-container-empty" id="section-about">`
`<div class="gb-inside-container"></div>`
`</section>`

Here is the same container's markup with version 1.5.0-rc.1

`<section class="block-editor-block-list__block wp-block gb-container gb-container-9aa050e7 gb-container-empty is-selected wp-block-generateblocks-container" id="block-05356d9a-892a-4b4a-aae6-898f4f7ed86e" data-align="full" tabindex="0" role="document" aria-label="Block: Container" data-block="05356d9a-892a-4b4a-aae6-898f4f7ed86e" data-type="generateblocks/container" data-title="Container">`
`<div class="gb-inside-container"></div>`
`</section>`

-----

**Comment by tomusborne** [comment]
This is due to our switch to `apiVersion: 2` in 1.5: https://make.wordpress.org/core/2020/11/18/block-api-version-2/

Before, there was an extra wrapper around our block HTML with the `block-{ $clientId }` ID attribute.

Now in version 2 that ID attribute is added to our block HTML, and seems to overwrite our own specified ID. The same thing seems to happen with the core Group block.

I assume that ID is necessary for Gutenberg to function which is why they overwrite the user-input ID.

Going to close this, but feel free to add more info if needed. If there's a core-friendly way to fix this I'd certainly be open to it.

**Comment by aaronbowden** [comment]
Appreciate the update Tom!

Wondering if that user defined ID could be visible on the editor side in a different form like a data-* attribute. That way it could still be targeted if needed.
