### ISSUE TITLE
Featured Image Caption

### ISSUE THREAD

**Issue by atmostfear-entertainment** [tomusborne/generateblocks#637]
We may be missing something since the newest version of GenerateBlocks is relatively new, and we are yet to explore all possibilities. If that is the case, we wish to apologize beforehand, and hopefully, your team will be able to point us in the right direction.

We have been actively redoing some of our Containers and using the new and powerful Query Loop feature. However, while setting it to display Single Posts, we have noticed that the Image Block does not include the option to add the Image Caption to such images.

As an alternative academic hybrid that does credits all the photographs used sitewide - photographs which in most cases are either provided by said photographers or purchased through stock image services - it is of the utmost importance that such credits are displayed publically to anyone accessing our website, this not only to avoid the reception of submissions asking us for the proper credits and proof of purchase but as well as to publically credit their authors such as we do with each article we publish while displaying the photograph and name of the author of said article.

If we are not wrong and such an option does not exist, please consider adding this feature as much as it would benefit us, as well as any other media that requires proper image credits to be displayed to avoid legal implications. In our specific case, we would like to see it included in a manner that it can be displayed on top of the Featured Image, in the bottom left corner, and not below the Feature Image, as doing such would cause all Query Loops to be displayed with credits below, prior to the title for instance, which is the format we use, even thus we are aware that Titles can be moved, aesthetically, this works best for us.

**Comment by JeanPaiva** [comment]
Hey @atmostfear-entertainment we have caption support already, you can added it clicking in the icon "CC" in the toolbar

![image](https://user-images.githubusercontent.com/7506830/179327021-39d28034-778f-4ab7-8d73-835e822def64.png)

Since the caption is just regular Headline block you can use dynamic data to display the image caption defined in the media library or any other field you may need.

![image](https://user-images.githubusercontent.com/7506830/179327101-aea20f5c-2cce-490d-a1b7-b9fb89c5d380.png)

This will give you dynamic caption below your featured image and you can apply any styles you want as you would normally do for a Headline block. Hope that helps you. :)
