### ISSUE TITLE
Add Container layout selector

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generateblocks#965]
Container blocks when added to the root of a page should give the users a choice between adding a plain container or a container with an inner container inside of it.

**Comment by Calvin-Susan** [comment]
Question, and I'm sure you've already thought this through and have a good reason.... But what about simply adding a "section" block?  The distinction would be a section block would have the <section> tag, plus an inner container (with a max-width and margin-inline: auto). A container block would not have those things.

This way, instead of having to do an "extra" click to make a choice, you just use the appropriate block.

**Comment by tomusborne** [comment]
@Calvin-Susan This was the original idea, but it was vetoed as the name "Section" is somewhat reserved by the `section` html tag. We were afraid it would cause more confusion.

Something we've noticed is users adding the "Container" block as they always have, but then being confused that there is no width/centering by default.

This issue aims to solve the problem by adding a layout selector if the Container block is added at the top-level, giving the user a choice of adding a "Section" or a plain Container block.
